### ISSUE TITLE
Extending the schema

### ISSUE THREAD

**Issue by ckoscher** [CrossRef/niso-ali#2]
Looking for any comments.

In planning our move to adopt the ali.xsd we have a need to extend the definition to incorporate a preexisting attribute from our internal schema (which has been in use for several months prior to the issuance of the Niso schema).

To achieve this I've proposed changing the Niso schema as follows:
![screen shot 2015-02-13 at 11 06 03 am](https://cloud.githubusercontent.com/assets/2117444/6190494/609be9d8-b370-11e4-8749-642203c55321.png)

This allows me to then use xsd:redefine to extend license_ref_t with our attribute.

Chuck

**Comment by kjw** [comment]
Naming the types defined by the schema doesn't affect anything from the perspective of the NISO recommendation. In fact it doesn't affect how people will use the schema at all. Thus there's no reason to reject this change.

Unsure of the approach CrossRef could take with `xsd:redefine`. Seems reasonable but I don't know much about `xsd:redefine`. I understand the concept of type extension but type redefinition (while maintaining the same schema name) is new to me.

**Comment by kjw** [comment]
@ckoscher , is there any problem with allowing both `nisoali:license_ref` and `crossrefali:license_ref` to coexist within the CrossRef deposit schema? Those wanting to include additional information or maintain their existing deposit code could do so, while those who translate or pull directly from other NISO ALI compatible XML can use the new NISO schema.

We could later generate NISO ALI from CrossRef ALI when responding with metadata.

One problem otherwise is that we redefine the NISO schema just for CrossRef. The JATS standing committee seems intent on getting NISO ALI and existing JATS license reference information working together. So we would be setting up CrossRef as the odd one out.

**Comment by kjw** [comment]
Some further information on `redefine` - it appears to be deprecated:

> Note: The redefinition feature described in the remainder of this section is ·deprecated· and may be removed from future versions of this specification. Schema authors are encouraged to avoid its use in cases where interoperability or compatibility with later versions of this specification are important.

http://www.w3.org/TR/xmlschema11-1/#modify-schema

**Comment by ckoscher** [comment]
Being deprecated I would not want to go down that path.  With that, the cleanest way forward would be to add the Niso free_to_read element to our schema

**Comment by kjw** [comment]
OK so explicitly:
1. We will add `free_to_read` to our deposit schema to take us to a _superset_ of the NISO ALI schema functionality, giving us functional compatibility on deposit.
2. We can then generate NISO ALI and include that in our UNIXSD and other XML response formats along side the CrossRef ALI elements. This gives us namespace compatibility on response.

This match your conclusion, @ckoscher ?

**Comment by ckoscher** [comment]
We will add &lt;free_to_read&gt;  by adding the element definition to our deposit schema giving us data compatibility. &lt;license_ref&gt; will continue to be our own element which as you point out is a super-set of the NISO ALI. 
As for generating NISO ALI on output, lets see what requirements unfold.
